SET SESSION FOREIGN_KEY_CHECKS=0;


/* Create Tables */
CREATE TABLE ods_z_tag
(
	ID VARCHAR(64) NOT NULL COMMENT '编号',
	STAN_CD_NO VARCHAR(10) NOT NULL COMMENT '标准代码编号',
	STAN_CD_DESC VARCHAR(200) COMMENT '标准代码描述',
	STATUS CHAR(1) DEFAULT '0' NOT NULL COMMENT '状态（0正常 1删除 2停用）',
	CREATE_BY VARCHAR(64) NOT NULL COMMENT '创建者',
	CREATE_DATE DATETIME NOT NULL COMMENT '创建时间',
	UPDATE_BY VARCHAR(64) NOT NULL COMMENT '更新者',
	UPDATE_DATE DATETIME NOT NULL COMMENT '更新时间',
	REMARKS VARCHAR(500) COMMENT '备注信息',
	PRIMARY KEY (ID)
) COMMENT = '标准代码';
ALTER TABLE ods_z_tag ADD UNIQUE uni_tag_no(STAN_CD_NO);

CREATE TABLE ods_z_tag_val
(
	ID VARCHAR(64) NOT NULL COMMENT '编号',
	STAN_CD_NO VARCHAR(10) NOT NULL COMMENT '标准代码编号',
	STAN_CD_VAL VARCHAR(100) NOT NULL COMMENT '标准代码',
	STAN_CD_DESC VARCHAR(100) COMMENT '标准代码值',
	STATUS CHAR(1) DEFAULT '0' NOT NULL COMMENT '状态（0正常 1删除 2停用）',
	CREATE_BY VARCHAR(64) NOT NULL COMMENT '创建者',
	CREATE_DATE DATETIME NOT NULL COMMENT '创建时间',
	UPDATE_BY VARCHAR(64) NOT NULL COMMENT '更新者',
	UPDATE_DATE DATETIME NOT NULL COMMENT '更新时间',
	REMARKS VARCHAR(500) COMMENT '备注信息',
	PRIMARY KEY (ID)
) COMMENT = '标准代码值';
ALTER TABLE ods_z_tag_val ADD UNIQUE uni_tag_no_val(STAN_CD_NO,STAN_CD_VAL);

CREATE TABLE ods_z_tag_trf
(
	ID VARCHAR(64) NOT NULL COMMENT '编号',
	SYSTEM_ID  VARCHAR(10) NOT NULL COMMENT '系统编号',
	TABLE_NM   VARCHAR(40) NOT NULL COMMENT '表名',
	COLUMN_NM  VARCHAR(40) NOT NULL COMMENT '字段名',
	SOURCE_CD VARCHAR(10) NOT NULL COMMENT '原系统代码',
	SOURCE_CD_DESC VARCHAR(200) COMMENT '代码含义',
	STAN_CD_NO VARCHAR(10) NOT NULL COMMENT '数据平台代码',
	STAN_CD_DESC VARCHAR(100) COMMENT '标准代码值',
	STATUS CHAR(1) DEFAULT '0' NOT NULL COMMENT '状态（0正常 1删除 2停用）',
	CREATE_BY VARCHAR(64) NOT NULL COMMENT '创建者',
	CREATE_DATE DATETIME NOT NULL COMMENT '创建时间',
	UPDATE_BY VARCHAR(64) NOT NULL COMMENT '更新者',
	UPDATE_DATE DATETIME NOT NULL COMMENT '更新时间',
	REMARKS VARCHAR(500) COMMENT '备注信息',
	PRIMARY KEY (ID)
) COMMENT = '标准代码转码';
ALTER TABLE ods_z_tag_trf ADD UNIQUE uni_tag_tab_col_no(TABLE_NM,COLUMN_NM,STAN_CD_NO);